### ISSUE TITLE
image

### ISSUE THREAD

**Issue by CharlieDinh** [CharlieDinh/FEDL#1]
[FEDL_updated.pdf](https://github.com/CharlieDinh/FEDL/files/4947913/FEDL_updated.pdf)
![Effects_of_eta](https://user-images.githubusercontent.com/44039773/87938445-f546e700-cad9-11ea-8138-a0b6f5e68419.png)
![mnist_test_accu](https://user-images.githubusercontent.com/44039773/87938456-f8da6e00-cad9-11ea-8ed2-9dbf8f5d245d.png)
![mnist_train_loss](https://user-images.githubusercontent.com/44039773/87938464-fa0b9b00-cad9-11ea-9a5f-b68e52b4f13d.png)
![nist_test_accu](https://user-images.githubusercontent.com/44039773/87938469-fb3cc800-cad9-11ea-9af5-11f91ba14e5b.png)
![nist_train_loss](https://user-images.githubusercontent.com/44039773/87938476-fd068b80-cad9-11ea-95cb-72f075ab1471.png)
![Effects_of_eta2](https://user-images.githubusercontent.com/44039773/92860589-c561f300-f43b-11ea-9e47-0d63daccfb09.png)
![MNIST_test_acc_nonc_4users](https://user-images.githubusercontent.com/44039773/92860564-be3ae500-f43b-11ea-871d-8e7d45e4ea19.png)
![MNIST_train_loss_nonc_4users](https://user-images.githubusercontent.com/44039773/92860569-c004a880-f43b-11ea-9129-7f8ce12b18bc.png)
[FEDL_journal_updated.pdf](https://github.com/CharlieDinh/FEDL/files/5205902/FEDL_journal_updated.pdf)

**Comment by Abdullatif2** [comment]
I think you have used NIST datasets in wrong way. How to make all users use the same data samples. In addition, FMINST as In LEAF has 3550 users in total and you have used only 100.

**Comment by CharlieDinh** [comment]
Hi Abdullatif2. 
Thank you for your comment,
I did not use the FEMNIST dataset from LEAF. As I only consider 100 users, if I use FEMNIST from LEAF, the number of sample for each user is small (around 200 samples), so I follow the FEMNIST used in the paper "https://github.com/litian96/FedProx". We use the same generation way with FedProx, but smaller number of users and larger sample sizes for each user.

**Comment by Abdullatif2** [comment]
Anyway, even with 100 users, it not practical to have the same data for all users, the FL assumed that the data is massively distributed and each user has his own style, distribution. In your work, all users use the same x and y. HOW?

**Comment by CharlieDinh** [comment]
how do you say that the data has the same x, y? they have different x and y.
