### ISSUE TITLE
Issue with tensorflow version 

### ISSUE THREAD

**Issue by ramshi236** [CharlieDinh/FEDL#2]
Hello Charlie ,my name is Ram and i am an electrical engineer grad student . I am trying to run your code but i keep getting an error that 
![image](https://user-images.githubusercontent.com/72392859/98536238-1f423600-2290-11eb-873a-51235cb1d6e9.png)
it seems that it cant find the attributes of tensorflow 
did you used the last version of tensorflow ?

**Comment by CharlieDinh** [comment]
Hi. I think the problem is the TensorFlow version. I guess you are using Ver2 while my code is implemented by Ver1.13. I will try to upgrade the code soon. But I recommend using my PyTorch version.

**Comment by CharlieDinh** [comment]
https://github.com/CharlieDinh/FEDL_pytorch

**Comment by CharlieDinh** [comment]
I updated the code to adapt with tensor version 2.0
