### ISSUE TITLE
TDMA to OFDM

### ISSUE THREAD

**Issue by 111tobestronger** [CharlieDinh/FEDL#3]
Could someone tell me which part of the author's code embodies time division multiple access, and how to change it to frequency division multiple access? Could you give me some guidance?

**Comment by CharlieDinh** [comment]
Hi,
maybe the code you need come from this repo
https://github.com/nhatminh/FEDL-INFOCOM

**Comment by 111tobestronger** [comment]
Hi,
The link you sent is very helpful to me. And I saw that the code in this link was also written by you, so I have a question. 
How does this code work. Which one of the three ‘Julia’ folders to choose to run? Is it necessary to run federated-learning-master before running Julia? Thank you very much for your answers.

**Comment by CharlieDinh** [comment]
Hi,

Sorry, I didn't know about Julia part. It could be better if you can contact  (nhatminh-Minh N. H. Nguyen) for this question.

Regards,
Canh Dinh

**Comment by 111tobestronger** [comment]
Hi,
I got it. Thank you very much for your answers.

**Comment by CharlieDinh** [comment]
No worries. :D
